/** GENERATED by tools/generate-motion-backgrounds.mjs — do not edit by hand. */
export interface MotionAssetEntry {
  id: string;
  name: string;
  kind: 'video' | 'image' | 'equirect';
  /** Absolute site path, e.g. '/motion/bg/earth_orbit.mp4' */
  file: string;
  /** Poster/thumbnail path used by the picker UI. */
  poster?: string;
  credit: string;
  tags: string[];
}

export const MOTION_ASSETS: MotionAssetEntry[] = [
  { id: 'earth_orbit', name: 'Earth From Orbit', kind: 'video', file: '/motion/bg/earth_orbit.mp4', poster: '/motion/bg/earth_orbit.jpg', credit: 'NASA', tags: ['space', 'earth', 'orbit'] },
  { id: 'galaxy_andromeda', name: 'Andromeda Galaxy', kind: 'video', file: '/motion/bg/galaxy_andromeda.mp4', poster: '/motion/bg/galaxy_andromeda.jpg', credit: 'NASA / JPL-Caltech', tags: ['space', 'galaxy', 'andromeda'] },
  { id: 'nebula_deep', name: 'Carina Nebula', kind: 'video', file: '/motion/bg/nebula_deep.mp4', poster: '/motion/bg/nebula_deep.jpg', credit: 'NASA / ESA / CSA / STScI', tags: ['space', 'nebula', 'carina'] },
  { id: 'deep_field', name: 'Hubble Deep Field', kind: 'video', file: '/motion/bg/deep_field.mp4', poster: '/motion/bg/deep_field.jpg', credit: 'NASA / ESA / STScI', tags: ['space', 'deep field', 'galaxies'] },
  { id: 'world_map', name: 'World Topography Map', kind: 'video', file: '/motion/bg/world_map.mp4', poster: '/motion/bg/world_map.jpg', credit: 'NASA Visible Earth', tags: ['earth', 'map', 'topography'] },
  { id: 'earth_equirect', name: 'Earth Equirectangular Map', kind: 'equirect', file: '/motion/bg/earth_equirect.jpg', credit: 'NASA Visible Earth', tags: ['earth', 'map', 'globe', 'equirectangular'] },
];
