#!/usr/bin/env node
/**
 * Create Stripe products/prices and sync IDs to Supabase secrets.
 * Requires STRIPE_SECRET_KEY in .env (use sk_live_... for production).
 *
 * Run: npm run setup:stripe
 */
import { readFileSync, existsSync, writeFileSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import Stripe from 'stripe';

const CATALOG = [
  { product: 'video_mixer', name: 'CloudCast Video Mixer', plans: [
    { id: 'pro', amount: 2900, name: 'Pro' },
    { id: 'pro_master', amount: 7900, name: 'Pro Master' },
  ]},
  { product: 'audio_mixer', name: 'CloudCast Audio Mixer', plans: [
    { id: 'pro', amount: 2900, name: 'Pro' },
    { id: 'pro_master', amount: 7900, name: 'Pro Master' },
  ]},
  { product: 'symphony_studio', name: 'CloudCast Symphony', plans: [
    { id: 'pro', amount: 2900, name: 'Pro' },
    { id: 'pro_master', amount: 7900, name: 'Pro Master' },
  ]},
  { product: 'regal_prism', name: 'Regal Prism', plans: [
    { id: 'pro', amount: 4900, name: 'Pro' },
    { id: 'pro_master', amount: 12900, name: 'Pro Master' },
  ]},
  { product: 'universal', name: 'CloudCast Universal', plans: [
    { id: 'universal_essential', amount: 5900, name: 'Universal Essential' },
    { id: 'universal_studio', amount: 9900, name: 'Universal Studio' },
    { id: 'universal', amount: 14900, name: 'Universal Master' },
  ]},
];

function loadEnv() {
  for (const file of ['.env', '.env.local']) {
    const path = join(process.cwd(), file);
    if (!existsSync(path)) continue;
    for (const line of readFileSync(path, 'utf8').split('\n')) {
      const m = line.match(/^([^#=]+)=(.*)$/);
      if (m && !process.env[m[1].trim()]) process.env[m[1].trim()] = m[2].trim();
    }
  }
}

function priceEnvKey(product, planId) {
  return `STRIPE_PRICE_${product}_${planId}`.toUpperCase();
}

loadEnv();

const secretKey = process.env.STRIPE_SECRET_KEY?.trim();
if (!secretKey) {
  console.error('Missing STRIPE_SECRET_KEY in .env');
  console.error('Get your secret key from https://dashboard.stripe.com/apikeys');
  process.exit(1);
}

const stripe = new Stripe(secretKey, { apiVersion: '2025-02-24.acacia' });
const isLive = secretKey.startsWith('sk_live_');
console.log(`CloudCast Stripe setup (${isLive ? 'LIVE' : 'TEST'} mode)\n`);

const priceIds = {};
const envLines = [];

for (const entry of CATALOG) {
  const existingProducts = await stripe.products.search({
    query: `metadata['cloudcast_product']:'${entry.product}'`,
    limit: 1,
  });

  let product = existingProducts.data[0];
  if (!product) {
    product = await stripe.products.create({
      name: entry.name,
      metadata: { cloudcast_product: entry.product },
    });
    console.log(`✓ Created product ${entry.name}`);
  } else {
    console.log(`· Product exists ${entry.name}`);
  }

  for (const plan of entry.plans) {
    const envKey = priceEnvKey(entry.product, plan.id);
    const existingEnv = process.env[envKey];
    if (existingEnv?.startsWith('price_')) {
      priceIds[envKey] = existingEnv;
      console.log(`· Price ${envKey} from .env`);
      continue;
    }

    const prices = await stripe.prices.list({ product: product.id, active: true, limit: 20 });
    let price = prices.data.find(
      (p) =>
        p.metadata?.cloudcast_plan === plan.id &&
        p.unit_amount === plan.amount &&
        p.recurring?.interval === 'month',
    );

    if (!price) {
      price = await stripe.prices.create({
        product: product.id,
        unit_amount: plan.amount,
        currency: 'usd',
        recurring: { interval: 'month' },
        nickname: `${entry.name} ${plan.name}`,
        metadata: { cloudcast_product: entry.product, cloudcast_plan: plan.id },
      });
      console.log(`✓ Created price ${plan.name} $${plan.amount / 100}/mo → ${price.id}`);
    } else {
      console.log(`· Price exists ${plan.name} → ${price.id}`);
    }

    priceIds[envKey] = price.id;
    envLines.push(`${envKey}=${price.id}`);
  }
}

const envPath = join(process.cwd(), '.env');
const stripeBlock = [
  '',
  '# Stripe (generated by npm run setup:stripe)',
  `VITE_STRIPE_ENABLED=true`,
  `VITE_APP_URL=${process.env.APP_PUBLIC_URL?.trim() || process.env.VITE_APP_URL?.trim() || 'https://cloudcast.live'}`,
  ...envLines,
  process.env.STRIPE_WEBHOOK_SECRET ? `STRIPE_WEBHOOK_SECRET=${process.env.STRIPE_WEBHOOK_SECRET}` : '# STRIPE_WEBHOOK_SECRET=whsec_... (from Stripe webhook dashboard)',
].join('\n');

if (existsSync(envPath)) {
  let content = readFileSync(envPath, 'utf8');
  if (!content.includes('STRIPE_PRICE_video_mixer_pro')) {
    appendFileSync(envPath, stripeBlock + '\n');
    console.log('\n✓ Appended Stripe price IDs to .env');
  } else {
    console.log('\n· .env already contains Stripe price IDs — updating secrets only');
  }
} else {
  writeFileSync(envPath, stripeBlock + '\n');
  console.log('\n✓ Wrote .env with Stripe price IDs');
}

// Reload env with new price IDs
loadEnv();
for (const [k, v] of Object.entries(priceIds)) {
  process.env[k] = v;
}

const secretPairs = {
  STRIPE_SECRET_KEY: secretKey,
  APP_PUBLIC_URL: process.env.APP_PUBLIC_URL?.trim() || 'https://cloudcast.live',
  ...priceIds,
};
if (process.env.STRIPE_WEBHOOK_SECRET?.trim()) {
  secretPairs.STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET.trim();
}

const args = ['secrets', 'set', ...Object.entries(secretPairs).flatMap(([k, v]) => [`${k}=${v}`])];
const result = spawnSync('supabase', args, { stdio: 'inherit' });
if (result.status !== 0) process.exit(result.status ?? 1);

const webhookUrl = 'https://ixjydnkpnyxnckhkqhue.supabase.co/functions/v1/stripe-webhook';
console.log(`
✓ Stripe catalog ready.

Next steps for production:
1. Stripe Dashboard → Developers → Webhooks → Add endpoint
   URL: ${webhookUrl}
   Events: checkout.session.completed, customer.subscription.updated, customer.subscription.deleted, invoice.payment_failed
2. Copy signing secret → STRIPE_WEBHOOK_SECRET in .env
3. Run: npm run secrets:stripe && npm run deploy:stripe
4. Enable Customer Portal: Stripe Dashboard → Settings → Billing → Customer portal
`);
